'use client';

import Navbar from '@/components/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import MainPage from '@/components/MainPage';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='dark'>
      <body className={inter.className}>
        <Navbar />
        <MainPage />
        {children}
      </body>
    </html>
  );
}
